version: "3.8"
services:
  nuxt-app-init:
    user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
    build:
      context: "${DOCKERFILE_DIRECTORY}"
      args:
        - DOCKER_USER_UID=${DOCKER_USER_UID}
        - DOCKER_USER_GID=${DOCKER_USER_GID}
    volumes:
      - "${PARENT_DIRECTORY}:/home/node/src"
    command: "npx nuxi init ${PROJECT_DIRECTORY}"