version: "3.8"
services:
  nuxt-app-init:
    user: ${DOCKER_USER_UID}:${DOCKER_USER_GID}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PARENT_DIRECTORY}:/src
    command: "npx nuxi init ${PROJECT_DIRECTORY}"